import NavBar from '@/components/NavBar'
import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer'
import { GlobalContextProvider } from '@/context/test'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    // <html lang="en">
    //   <body className={inter.className}>
        <main className='min-h-screen flex flex-col justify-between'>
          <NavBar/>
          <main className='min-w-full min-h-full'>
          <GlobalContextProvider>{children}</GlobalContextProvider>
    {/* {children} */}
          </main>
          <Footer/>
        </main>
    //   </body>
    // </html>
  )
}
